javac -cp . TJasn/virtualMachine/ADDinstr.java
javac -cp . TJasn/virtualMachine/ANDinstr.java
javac -cp . TJasn/virtualMachine/CALLSTATMETHODinstr.java
javac -cp . TJasn/virtualMachine/CHANGESIGNinstr.java
javac -cp . TJasn/virtualMachine/DIVinstr.java
javac -cp . TJasn/virtualMachine/EQinstr.java
javac -cp . TJasn/virtualMachine/GEinstr.java
javac -cp . TJasn/virtualMachine/GTinstr.java
javac -cp . TJasn/virtualMachine/INITSTKFRMinstr.java
javac -cp . TJasn/virtualMachine/JUMPinstr.java
javac -cp . TJasn/virtualMachine/JUMPONFALSEinstr.java
javac -cp . TJasn/virtualMachine/LEinstr.java
javac -cp . TJasn/virtualMachine/LOADFROMADDRinstr.java
javac -cp . TJasn/virtualMachine/LTinstr.java
javac -cp . TJasn/virtualMachine/MODinstr.java
javac -cp . TJasn/virtualMachine/MULinstr.java
javac -cp . TJasn/virtualMachine/NEinstr.java
javac -cp . TJasn/virtualMachine/NOTinstr.java
javac -cp . TJasn/virtualMachine/ORinstr.java
javac -cp . TJasn/virtualMachine/PASSPARAMinstr.java
javac -cp . TJasn/virtualMachine/PUSHLOCADDRinstr.java
javac -cp . TJasn/virtualMachine/PUSHNUMinstr.java
javac -cp . TJasn/virtualMachine/STATADDRinstr.java
javac -cp . TJasn/virtualMachine/PUSHSTATADDRinstr.java
javac -cp . TJasn/virtualMachine/RETURNinstr.java
javac -cp . TJasn/virtualMachine/SAVETOADDRinstr.java
javac -cp . TJasn/virtualMachine/SUBinstr.java
javac -cp . TJasn/virtualMachine/WRITEINTinstr.java
javac -cp . TJasn/virtualMachine/WRITESTRINGinstr.java